//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rest_application
{
    using System;
    using System.Collections.Generic;
    
    public partial class Entrenamiento
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Entrenamiento()
        {
            this.DetallePedido = new HashSet<DetallePedido>();
            this.Inscripciones = new HashSet<Inscripciones>();
        }
    
        public int codigoEntrenamiento { get; set; }
        public string tipo { get; set; }
        public System.DateTime fechaHora { get; set; }
        public decimal duracion { get; set; }
        public string ubicacion { get; set; }
        public int capacidadMaxima { get; set; }
        public bool estado { get; set; }
        public int codigoTrainer { get; set; }
        public int codigoLocal { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetallePedido> DetallePedido { get; set; }
        public virtual Trainer Trainer { get; set; }
        public virtual Locales Locales { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Inscripciones> Inscripciones { get; set; }
    }
}
