//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rest_application
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inscripciones
    {
        public int codigoInscripcion { get; set; }
        public int codigoCliente { get; set; }
        public int codigoEntrenamiento { get; set; }
        public System.DateTime fechaInscripcion { get; set; }
        public bool estado { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual Entrenamiento Entrenamiento { get; set; }
    }
}
