//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvc_application
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class SmarfitEntities : DbContext
    {
        public SmarfitEntities()
            : base("name=SmarfitEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cliente> Cliente { get; set; }
        public virtual DbSet<DetallePedido> DetallePedido { get; set; }
        public virtual DbSet<Entrenamiento> Entrenamiento { get; set; }
        public virtual DbSet<Inscripciones> Inscripciones { get; set; }
        public virtual DbSet<Locales> Locales { get; set; }
        public virtual DbSet<Pedido> Pedido { get; set; }
        public virtual DbSet<Reclamo> Reclamo { get; set; }
        public virtual DbSet<Sancion> Sancion { get; set; }
        public virtual DbSet<Trainer> Trainer { get; set; }
    
        public virtual int SP_ActualizarCliente(Nullable<int> codigoCliente, string nombre, string correo, string telefono, string direccion, string historialEntrenamientos, Nullable<bool> estado)
        {
            var codigoClienteParameter = codigoCliente.HasValue ?
                new ObjectParameter("codigoCliente", codigoCliente) :
                new ObjectParameter("codigoCliente", typeof(int));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            var correoParameter = correo != null ?
                new ObjectParameter("correo", correo) :
                new ObjectParameter("correo", typeof(string));
    
            var telefonoParameter = telefono != null ?
                new ObjectParameter("telefono", telefono) :
                new ObjectParameter("telefono", typeof(string));
    
            var direccionParameter = direccion != null ?
                new ObjectParameter("direccion", direccion) :
                new ObjectParameter("direccion", typeof(string));
    
            var historialEntrenamientosParameter = historialEntrenamientos != null ?
                new ObjectParameter("historialEntrenamientos", historialEntrenamientos) :
                new ObjectParameter("historialEntrenamientos", typeof(string));
    
            var estadoParameter = estado.HasValue ?
                new ObjectParameter("estado", estado) :
                new ObjectParameter("estado", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_ActualizarCliente", codigoClienteParameter, nombreParameter, correoParameter, telefonoParameter, direccionParameter, historialEntrenamientosParameter, estadoParameter);
        }
    
        public virtual int SP_ActualizarDetallePedido(Nullable<int> codigoDetallePedido, Nullable<int> cantidad, Nullable<decimal> precioUnitario, Nullable<bool> estado)
        {
            var codigoDetallePedidoParameter = codigoDetallePedido.HasValue ?
                new ObjectParameter("codigoDetallePedido", codigoDetallePedido) :
                new ObjectParameter("codigoDetallePedido", typeof(int));
    
            var cantidadParameter = cantidad.HasValue ?
                new ObjectParameter("cantidad", cantidad) :
                new ObjectParameter("cantidad", typeof(int));
    
            var precioUnitarioParameter = precioUnitario.HasValue ?
                new ObjectParameter("precioUnitario", precioUnitario) :
                new ObjectParameter("precioUnitario", typeof(decimal));
    
            var estadoParameter = estado.HasValue ?
                new ObjectParameter("estado", estado) :
                new ObjectParameter("estado", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_ActualizarDetallePedido", codigoDetallePedidoParameter, cantidadParameter, precioUnitarioParameter, estadoParameter);
        }
    
        public virtual int SP_ActualizarEntrenamiento(Nullable<int> codigo, string tipo, Nullable<System.DateTime> fechaHora, Nullable<decimal> duracion, string ubicacion, Nullable<int> capacidadMaxima, Nullable<bool> estado, Nullable<int> codigoTrainer, Nullable<int> codigoLocal)
        {
            var codigoParameter = codigo.HasValue ?
                new ObjectParameter("codigo", codigo) :
                new ObjectParameter("codigo", typeof(int));
    
            var tipoParameter = tipo != null ?
                new ObjectParameter("tipo", tipo) :
                new ObjectParameter("tipo", typeof(string));
    
            var fechaHoraParameter = fechaHora.HasValue ?
                new ObjectParameter("fechaHora", fechaHora) :
                new ObjectParameter("fechaHora", typeof(System.DateTime));
    
            var duracionParameter = duracion.HasValue ?
                new ObjectParameter("duracion", duracion) :
                new ObjectParameter("duracion", typeof(decimal));
    
            var ubicacionParameter = ubicacion != null ?
                new ObjectParameter("ubicacion", ubicacion) :
                new ObjectParameter("ubicacion", typeof(string));
    
            var capacidadMaximaParameter = capacidadMaxima.HasValue ?
                new ObjectParameter("capacidadMaxima", capacidadMaxima) :
                new ObjectParameter("capacidadMaxima", typeof(int));
    
            var estadoParameter = estado.HasValue ?
                new ObjectParameter("estado", estado) :
                new ObjectParameter("estado", typeof(bool));
    
            var codigoTrainerParameter = codigoTrainer.HasValue ?
                new ObjectParameter("codigoTrainer", codigoTrainer) :
                new ObjectParameter("codigoTrainer", typeof(int));
    
            var codigoLocalParameter = codigoLocal.HasValue ?
                new ObjectParameter("codigoLocal", codigoLocal) :
                new ObjectParameter("codigoLocal", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_ActualizarEntrenamiento", codigoParameter, tipoParameter, fechaHoraParameter, duracionParameter, ubicacionParameter, capacidadMaximaParameter, estadoParameter, codigoTrainerParameter, codigoLocalParameter);
        }
    
        public virtual int SP_ActualizarLocales(Nullable<int> codigoLocal, string tipo, string direccion, Nullable<int> capacidadMaxima, Nullable<bool> estado)
        {
            var codigoLocalParameter = codigoLocal.HasValue ?
                new ObjectParameter("codigoLocal", codigoLocal) :
                new ObjectParameter("codigoLocal", typeof(int));
    
            var tipoParameter = tipo != null ?
                new ObjectParameter("tipo", tipo) :
                new ObjectParameter("tipo", typeof(string));
    
            var direccionParameter = direccion != null ?
                new ObjectParameter("direccion", direccion) :
                new ObjectParameter("direccion", typeof(string));
    
            var capacidadMaximaParameter = capacidadMaxima.HasValue ?
                new ObjectParameter("capacidadMaxima", capacidadMaxima) :
                new ObjectParameter("capacidadMaxima", typeof(int));
    
            var estadoParameter = estado.HasValue ?
                new ObjectParameter("estado", estado) :
                new ObjectParameter("estado", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_ActualizarLocales", codigoLocalParameter, tipoParameter, direccionParameter, capacidadMaximaParameter, estadoParameter);
        }
    
        public virtual int SP_ActualizarPedido(Nullable<int> codigoPedido, Nullable<int> codigoCliente, Nullable<decimal> total, Nullable<bool> estado)
        {
            var codigoPedidoParameter = codigoPedido.HasValue ?
                new ObjectParameter("codigoPedido", codigoPedido) :
                new ObjectParameter("codigoPedido", typeof(int));
    
            var codigoClienteParameter = codigoCliente.HasValue ?
                new ObjectParameter("codigoCliente", codigoCliente) :
                new ObjectParameter("codigoCliente", typeof(int));
    
            var totalParameter = total.HasValue ?
                new ObjectParameter("total", total) :
                new ObjectParameter("total", typeof(decimal));
    
            var estadoParameter = estado.HasValue ?
                new ObjectParameter("estado", estado) :
                new ObjectParameter("estado", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_ActualizarPedido", codigoPedidoParameter, codigoClienteParameter, totalParameter, estadoParameter);
        }
    
        public virtual int SP_ActualizarReclamo(Nullable<int> codigo, string descripcion, Nullable<System.DateTime> fecha, Nullable<bool> estado, Nullable<int> codigoCliente)
        {
            var codigoParameter = codigo.HasValue ?
                new ObjectParameter("codigo", codigo) :
                new ObjectParameter("codigo", typeof(int));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("descripcion", descripcion) :
                new ObjectParameter("descripcion", typeof(string));
    
            var fechaParameter = fecha.HasValue ?
                new ObjectParameter("fecha", fecha) :
                new ObjectParameter("fecha", typeof(System.DateTime));
    
            var estadoParameter = estado.HasValue ?
                new ObjectParameter("estado", estado) :
                new ObjectParameter("estado", typeof(bool));
    
            var codigoClienteParameter = codigoCliente.HasValue ?
                new ObjectParameter("codigoCliente", codigoCliente) :
                new ObjectParameter("codigoCliente", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_ActualizarReclamo", codigoParameter, descripcionParameter, fechaParameter, estadoParameter, codigoClienteParameter);
        }
    
        public virtual int SP_ActualizarSancion(Nullable<int> codigo, Nullable<System.DateTime> fechaInicio, Nullable<System.DateTime> fechaFin, string motivo, Nullable<int> codigoCliente)
        {
            var codigoParameter = codigo.HasValue ?
                new ObjectParameter("codigo", codigo) :
                new ObjectParameter("codigo", typeof(int));
    
            var fechaInicioParameter = fechaInicio.HasValue ?
                new ObjectParameter("fechaInicio", fechaInicio) :
                new ObjectParameter("fechaInicio", typeof(System.DateTime));
    
            var fechaFinParameter = fechaFin.HasValue ?
                new ObjectParameter("fechaFin", fechaFin) :
                new ObjectParameter("fechaFin", typeof(System.DateTime));
    
            var motivoParameter = motivo != null ?
                new ObjectParameter("motivo", motivo) :
                new ObjectParameter("motivo", typeof(string));
    
            var codigoClienteParameter = codigoCliente.HasValue ?
                new ObjectParameter("codigoCliente", codigoCliente) :
                new ObjectParameter("codigoCliente", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_ActualizarSancion", codigoParameter, fechaInicioParameter, fechaFinParameter, motivoParameter, codigoClienteParameter);
        }
    
        public virtual int SP_ActualizarTrainer(Nullable<int> codigoTrainer, string nombre, string apellido, string especialidad, Nullable<bool> disponibilidad)
        {
            var codigoTrainerParameter = codigoTrainer.HasValue ?
                new ObjectParameter("codigoTrainer", codigoTrainer) :
                new ObjectParameter("codigoTrainer", typeof(int));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            var apellidoParameter = apellido != null ?
                new ObjectParameter("apellido", apellido) :
                new ObjectParameter("apellido", typeof(string));
    
            var especialidadParameter = especialidad != null ?
                new ObjectParameter("especialidad", especialidad) :
                new ObjectParameter("especialidad", typeof(string));
    
            var disponibilidadParameter = disponibilidad.HasValue ?
                new ObjectParameter("disponibilidad", disponibilidad) :
                new ObjectParameter("disponibilidad", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_ActualizarTrainer", codigoTrainerParameter, nombreParameter, apellidoParameter, especialidadParameter, disponibilidadParameter);
        }
    
        public virtual ObjectResult<SP_BuscarClienteXCodigo_Result> SP_BuscarClienteXCodigo(Nullable<int> codigoCliente)
        {
            var codigoClienteParameter = codigoCliente.HasValue ?
                new ObjectParameter("codigoCliente", codigoCliente) :
                new ObjectParameter("codigoCliente", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_BuscarClienteXCodigo_Result>("SP_BuscarClienteXCodigo", codigoClienteParameter);
        }
    
        public virtual ObjectResult<SP_BuscarDetallePedidoXCodigo_Result> SP_BuscarDetallePedidoXCodigo(Nullable<int> codigoDetallePedido)
        {
            var codigoDetallePedidoParameter = codigoDetallePedido.HasValue ?
                new ObjectParameter("codigoDetallePedido", codigoDetallePedido) :
                new ObjectParameter("codigoDetallePedido", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_BuscarDetallePedidoXCodigo_Result>("SP_BuscarDetallePedidoXCodigo", codigoDetallePedidoParameter);
        }
    
        public virtual ObjectResult<SP_BuscarEntrenamientoXCodigo_Result> SP_BuscarEntrenamientoXCodigo(Nullable<int> codigo)
        {
            var codigoParameter = codigo.HasValue ?
                new ObjectParameter("codigo", codigo) :
                new ObjectParameter("codigo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_BuscarEntrenamientoXCodigo_Result>("SP_BuscarEntrenamientoXCodigo", codigoParameter);
        }
    
        public virtual ObjectResult<SP_BuscarLocalesXCodigo_Result> SP_BuscarLocalesXCodigo(Nullable<int> codigoLocal)
        {
            var codigoLocalParameter = codigoLocal.HasValue ?
                new ObjectParameter("codigoLocal", codigoLocal) :
                new ObjectParameter("codigoLocal", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_BuscarLocalesXCodigo_Result>("SP_BuscarLocalesXCodigo", codigoLocalParameter);
        }
    
        public virtual ObjectResult<SP_BuscarPedidoXCodigo_Result> SP_BuscarPedidoXCodigo(Nullable<int> codigoPedido)
        {
            var codigoPedidoParameter = codigoPedido.HasValue ?
                new ObjectParameter("codigoPedido", codigoPedido) :
                new ObjectParameter("codigoPedido", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_BuscarPedidoXCodigo_Result>("SP_BuscarPedidoXCodigo", codigoPedidoParameter);
        }
    
        public virtual ObjectResult<SP_BuscarReclamoXCodigo_Result> SP_BuscarReclamoXCodigo(Nullable<int> codigo)
        {
            var codigoParameter = codigo.HasValue ?
                new ObjectParameter("codigo", codigo) :
                new ObjectParameter("codigo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_BuscarReclamoXCodigo_Result>("SP_BuscarReclamoXCodigo", codigoParameter);
        }
    
        public virtual ObjectResult<SP_BuscarSancionXCodigo_Result> SP_BuscarSancionXCodigo(Nullable<int> codigo)
        {
            var codigoParameter = codigo.HasValue ?
                new ObjectParameter("codigo", codigo) :
                new ObjectParameter("codigo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_BuscarSancionXCodigo_Result>("SP_BuscarSancionXCodigo", codigoParameter);
        }
    
        public virtual ObjectResult<SP_BuscarTrainerXCodigo_Result> SP_BuscarTrainerXCodigo(Nullable<int> codigoTrainer)
        {
            var codigoTrainerParameter = codigoTrainer.HasValue ?
                new ObjectParameter("codigoTrainer", codigoTrainer) :
                new ObjectParameter("codigoTrainer", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_BuscarTrainerXCodigo_Result>("SP_BuscarTrainerXCodigo", codigoTrainerParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> SP_CodigoCliente()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("SP_CodigoCliente");
        }
    
        public virtual ObjectResult<Nullable<int>> SP_CodigoDetallePedido()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("SP_CodigoDetallePedido");
        }
    
        public virtual ObjectResult<Nullable<int>> SP_CodigoEntrenamiento()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("SP_CodigoEntrenamiento");
        }
    
        public virtual ObjectResult<Nullable<int>> SP_CodigoLocales()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("SP_CodigoLocales");
        }
    
        public virtual ObjectResult<Nullable<int>> SP_CodigoPedido()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("SP_CodigoPedido");
        }
    
        public virtual ObjectResult<Nullable<int>> SP_CodigoReclamo()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("SP_CodigoReclamo");
        }
    
        public virtual ObjectResult<Nullable<int>> SP_CodigoSancion()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("SP_CodigoSancion");
        }
    
        public virtual ObjectResult<Nullable<int>> SP_CodigoTrainer()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("SP_CodigoTrainer");
        }
    
        public virtual int SP_EliminarCliente(Nullable<int> codigoCliente)
        {
            var codigoClienteParameter = codigoCliente.HasValue ?
                new ObjectParameter("codigoCliente", codigoCliente) :
                new ObjectParameter("codigoCliente", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_EliminarCliente", codigoClienteParameter);
        }
    
        public virtual int SP_EliminarDetallePedido(Nullable<int> codigoDetallePedido)
        {
            var codigoDetallePedidoParameter = codigoDetallePedido.HasValue ?
                new ObjectParameter("codigoDetallePedido", codigoDetallePedido) :
                new ObjectParameter("codigoDetallePedido", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_EliminarDetallePedido", codigoDetallePedidoParameter);
        }
    
        public virtual int SP_EliminarEntrenamiento(Nullable<int> codigo)
        {
            var codigoParameter = codigo.HasValue ?
                new ObjectParameter("codigo", codigo) :
                new ObjectParameter("codigo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_EliminarEntrenamiento", codigoParameter);
        }
    
        public virtual ObjectResult<string> SP_EliminarInscripcion(Nullable<int> codigoInscripcion)
        {
            var codigoInscripcionParameter = codigoInscripcion.HasValue ?
                new ObjectParameter("codigoInscripcion", codigoInscripcion) :
                new ObjectParameter("codigoInscripcion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("SP_EliminarInscripcion", codigoInscripcionParameter);
        }
    
        public virtual int SP_EliminarLocales(Nullable<int> codigoLocal)
        {
            var codigoLocalParameter = codigoLocal.HasValue ?
                new ObjectParameter("codigoLocal", codigoLocal) :
                new ObjectParameter("codigoLocal", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_EliminarLocales", codigoLocalParameter);
        }
    
        public virtual int SP_EliminarPedido(Nullable<int> codigoPedido)
        {
            var codigoPedidoParameter = codigoPedido.HasValue ?
                new ObjectParameter("codigoPedido", codigoPedido) :
                new ObjectParameter("codigoPedido", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_EliminarPedido", codigoPedidoParameter);
        }
    
        public virtual int SP_EliminarReclamo(Nullable<int> codigo)
        {
            var codigoParameter = codigo.HasValue ?
                new ObjectParameter("codigo", codigo) :
                new ObjectParameter("codigo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_EliminarReclamo", codigoParameter);
        }
    
        public virtual int SP_EliminarSancion(Nullable<int> codigo)
        {
            var codigoParameter = codigo.HasValue ?
                new ObjectParameter("codigo", codigo) :
                new ObjectParameter("codigo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_EliminarSancion", codigoParameter);
        }
    
        public virtual int SP_EliminarTrainer(Nullable<int> codigoTrainer)
        {
            var codigoTrainerParameter = codigoTrainer.HasValue ?
                new ObjectParameter("codigoTrainer", codigoTrainer) :
                new ObjectParameter("codigoTrainer", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_EliminarTrainer", codigoTrainerParameter);
        }
    
        public virtual int SP_HabilitarCliente(Nullable<int> codigoCliente)
        {
            var codigoClienteParameter = codigoCliente.HasValue ?
                new ObjectParameter("codigoCliente", codigoCliente) :
                new ObjectParameter("codigoCliente", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_HabilitarCliente", codigoClienteParameter);
        }
    
        public virtual int SP_HabilitarDetallePedido(Nullable<int> codigoDetallePedido)
        {
            var codigoDetallePedidoParameter = codigoDetallePedido.HasValue ?
                new ObjectParameter("codigoDetallePedido", codigoDetallePedido) :
                new ObjectParameter("codigoDetallePedido", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_HabilitarDetallePedido", codigoDetallePedidoParameter);
        }
    
        public virtual int SP_HabilitarEntrenamiento(Nullable<int> codigo)
        {
            var codigoParameter = codigo.HasValue ?
                new ObjectParameter("codigo", codigo) :
                new ObjectParameter("codigo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_HabilitarEntrenamiento", codigoParameter);
        }
    
        public virtual int SP_HabilitarLocales(Nullable<int> codigoLocal)
        {
            var codigoLocalParameter = codigoLocal.HasValue ?
                new ObjectParameter("codigoLocal", codigoLocal) :
                new ObjectParameter("codigoLocal", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_HabilitarLocales", codigoLocalParameter);
        }
    
        public virtual int SP_HabilitarPedido(Nullable<int> codigoPedido)
        {
            var codigoPedidoParameter = codigoPedido.HasValue ?
                new ObjectParameter("codigoPedido", codigoPedido) :
                new ObjectParameter("codigoPedido", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_HabilitarPedido", codigoPedidoParameter);
        }
    
        public virtual int SP_HabilitarReclamo(Nullable<int> codigo)
        {
            var codigoParameter = codigo.HasValue ?
                new ObjectParameter("codigo", codigo) :
                new ObjectParameter("codigo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_HabilitarReclamo", codigoParameter);
        }
    
        public virtual int SP_HabilitarTrainer(Nullable<int> codigoTrainer)
        {
            var codigoTrainerParameter = codigoTrainer.HasValue ?
                new ObjectParameter("codigoTrainer", codigoTrainer) :
                new ObjectParameter("codigoTrainer", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_HabilitarTrainer", codigoTrainerParameter);
        }
    
        public virtual ObjectResult<SP_MostrarCliente_Result> SP_MostrarCliente()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_MostrarCliente_Result>("SP_MostrarCliente");
        }
    
        public virtual ObjectResult<SP_MostrarClienteTodo_Result> SP_MostrarClienteTodo()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_MostrarClienteTodo_Result>("SP_MostrarClienteTodo");
        }
    
        public virtual ObjectResult<SP_MostrarDetallePedido_Result> SP_MostrarDetallePedido()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_MostrarDetallePedido_Result>("SP_MostrarDetallePedido");
        }
    
        public virtual ObjectResult<SP_MostrarDetallePedidoTodo_Result> SP_MostrarDetallePedidoTodo()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_MostrarDetallePedidoTodo_Result>("SP_MostrarDetallePedidoTodo");
        }
    
        public virtual ObjectResult<SP_MostrarEntrenamiento_Result> SP_MostrarEntrenamiento()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_MostrarEntrenamiento_Result>("SP_MostrarEntrenamiento");
        }
    
        public virtual ObjectResult<SP_MostrarEntrenamientoTodo_Result> SP_MostrarEntrenamientoTodo()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_MostrarEntrenamientoTodo_Result>("SP_MostrarEntrenamientoTodo");
        }
    
        public virtual ObjectResult<SP_MostrarInscripciones_Result> SP_MostrarInscripciones()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_MostrarInscripciones_Result>("SP_MostrarInscripciones");
        }
    
        public virtual ObjectResult<SP_MostrarInscripcionesPorCliente_Result> SP_MostrarInscripcionesPorCliente(Nullable<int> codigoCliente)
        {
            var codigoClienteParameter = codigoCliente.HasValue ?
                new ObjectParameter("codigoCliente", codigoCliente) :
                new ObjectParameter("codigoCliente", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_MostrarInscripcionesPorCliente_Result>("SP_MostrarInscripcionesPorCliente", codigoClienteParameter);
        }
    
        public virtual ObjectResult<SP_MostrarLocales_Result> SP_MostrarLocales()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_MostrarLocales_Result>("SP_MostrarLocales");
        }
    
        public virtual ObjectResult<SP_MostrarLocalesTodo_Result> SP_MostrarLocalesTodo()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_MostrarLocalesTodo_Result>("SP_MostrarLocalesTodo");
        }
    
        public virtual ObjectResult<SP_MostrarPedido_Result> SP_MostrarPedido()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_MostrarPedido_Result>("SP_MostrarPedido");
        }
    
        public virtual ObjectResult<SP_MostrarPedidoTodo_Result> SP_MostrarPedidoTodo()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_MostrarPedidoTodo_Result>("SP_MostrarPedidoTodo");
        }
    
        public virtual ObjectResult<SP_MostrarReclamo_Result> SP_MostrarReclamo()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_MostrarReclamo_Result>("SP_MostrarReclamo");
        }
    
        public virtual ObjectResult<SP_MostrarReclamoTodo_Result> SP_MostrarReclamoTodo()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_MostrarReclamoTodo_Result>("SP_MostrarReclamoTodo");
        }
    
        public virtual ObjectResult<SP_MostrarSancion_Result> SP_MostrarSancion()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_MostrarSancion_Result>("SP_MostrarSancion");
        }
    
        public virtual ObjectResult<SP_MostrarSancionTodo_Result> SP_MostrarSancionTodo()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_MostrarSancionTodo_Result>("SP_MostrarSancionTodo");
        }
    
        public virtual ObjectResult<SP_MostrarTrainer_Result> SP_MostrarTrainer()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_MostrarTrainer_Result>("SP_MostrarTrainer");
        }
    
        public virtual ObjectResult<SP_MostrarTrainerTodo_Result> SP_MostrarTrainerTodo()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_MostrarTrainerTodo_Result>("SP_MostrarTrainerTodo");
        }
    
        public virtual int SP_RegistrarCliente(string nombre, string correo, string telefono, string direccion, string historialEntrenamientos, Nullable<bool> estado)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            var correoParameter = correo != null ?
                new ObjectParameter("correo", correo) :
                new ObjectParameter("correo", typeof(string));
    
            var telefonoParameter = telefono != null ?
                new ObjectParameter("telefono", telefono) :
                new ObjectParameter("telefono", typeof(string));
    
            var direccionParameter = direccion != null ?
                new ObjectParameter("direccion", direccion) :
                new ObjectParameter("direccion", typeof(string));
    
            var historialEntrenamientosParameter = historialEntrenamientos != null ?
                new ObjectParameter("historialEntrenamientos", historialEntrenamientos) :
                new ObjectParameter("historialEntrenamientos", typeof(string));
    
            var estadoParameter = estado.HasValue ?
                new ObjectParameter("estado", estado) :
                new ObjectParameter("estado", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_RegistrarCliente", nombreParameter, correoParameter, telefonoParameter, direccionParameter, historialEntrenamientosParameter, estadoParameter);
        }
    
        public virtual int SP_RegistrarDetallePedido(Nullable<int> codigoPedido, Nullable<int> codigoEntrenamiento, Nullable<int> cantidad, Nullable<decimal> precioUnitario, Nullable<bool> estado)
        {
            var codigoPedidoParameter = codigoPedido.HasValue ?
                new ObjectParameter("codigoPedido", codigoPedido) :
                new ObjectParameter("codigoPedido", typeof(int));
    
            var codigoEntrenamientoParameter = codigoEntrenamiento.HasValue ?
                new ObjectParameter("codigoEntrenamiento", codigoEntrenamiento) :
                new ObjectParameter("codigoEntrenamiento", typeof(int));
    
            var cantidadParameter = cantidad.HasValue ?
                new ObjectParameter("cantidad", cantidad) :
                new ObjectParameter("cantidad", typeof(int));
    
            var precioUnitarioParameter = precioUnitario.HasValue ?
                new ObjectParameter("precioUnitario", precioUnitario) :
                new ObjectParameter("precioUnitario", typeof(decimal));
    
            var estadoParameter = estado.HasValue ?
                new ObjectParameter("estado", estado) :
                new ObjectParameter("estado", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_RegistrarDetallePedido", codigoPedidoParameter, codigoEntrenamientoParameter, cantidadParameter, precioUnitarioParameter, estadoParameter);
        }
    
        public virtual int SP_RegistrarEntrenamiento(string tipo, Nullable<System.DateTime> fechaHora, Nullable<decimal> duracion, string ubicacion, Nullable<int> capacidadMaxima, Nullable<bool> estado, Nullable<int> codigoTrainer, Nullable<int> codigoLocal)
        {
            var tipoParameter = tipo != null ?
                new ObjectParameter("tipo", tipo) :
                new ObjectParameter("tipo", typeof(string));
    
            var fechaHoraParameter = fechaHora.HasValue ?
                new ObjectParameter("fechaHora", fechaHora) :
                new ObjectParameter("fechaHora", typeof(System.DateTime));
    
            var duracionParameter = duracion.HasValue ?
                new ObjectParameter("duracion", duracion) :
                new ObjectParameter("duracion", typeof(decimal));
    
            var ubicacionParameter = ubicacion != null ?
                new ObjectParameter("ubicacion", ubicacion) :
                new ObjectParameter("ubicacion", typeof(string));
    
            var capacidadMaximaParameter = capacidadMaxima.HasValue ?
                new ObjectParameter("capacidadMaxima", capacidadMaxima) :
                new ObjectParameter("capacidadMaxima", typeof(int));
    
            var estadoParameter = estado.HasValue ?
                new ObjectParameter("estado", estado) :
                new ObjectParameter("estado", typeof(bool));
    
            var codigoTrainerParameter = codigoTrainer.HasValue ?
                new ObjectParameter("codigoTrainer", codigoTrainer) :
                new ObjectParameter("codigoTrainer", typeof(int));
    
            var codigoLocalParameter = codigoLocal.HasValue ?
                new ObjectParameter("codigoLocal", codigoLocal) :
                new ObjectParameter("codigoLocal", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_RegistrarEntrenamiento", tipoParameter, fechaHoraParameter, duracionParameter, ubicacionParameter, capacidadMaximaParameter, estadoParameter, codigoTrainerParameter, codigoLocalParameter);
        }
    
        public virtual ObjectResult<string> SP_RegistrarInscripcion(Nullable<int> codigoCliente, Nullable<int> codigoEntrenamiento)
        {
            var codigoClienteParameter = codigoCliente.HasValue ?
                new ObjectParameter("codigoCliente", codigoCliente) :
                new ObjectParameter("codigoCliente", typeof(int));
    
            var codigoEntrenamientoParameter = codigoEntrenamiento.HasValue ?
                new ObjectParameter("codigoEntrenamiento", codigoEntrenamiento) :
                new ObjectParameter("codigoEntrenamiento", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("SP_RegistrarInscripcion", codigoClienteParameter, codigoEntrenamientoParameter);
        }
    
        public virtual int SP_RegistrarLocales(string tipo, string direccion, Nullable<int> capacidadMaxima, Nullable<bool> estado)
        {
            var tipoParameter = tipo != null ?
                new ObjectParameter("tipo", tipo) :
                new ObjectParameter("tipo", typeof(string));
    
            var direccionParameter = direccion != null ?
                new ObjectParameter("direccion", direccion) :
                new ObjectParameter("direccion", typeof(string));
    
            var capacidadMaximaParameter = capacidadMaxima.HasValue ?
                new ObjectParameter("capacidadMaxima", capacidadMaxima) :
                new ObjectParameter("capacidadMaxima", typeof(int));
    
            var estadoParameter = estado.HasValue ?
                new ObjectParameter("estado", estado) :
                new ObjectParameter("estado", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_RegistrarLocales", tipoParameter, direccionParameter, capacidadMaximaParameter, estadoParameter);
        }
    
        public virtual int SP_RegistrarPedido(Nullable<int> codigoCliente, Nullable<decimal> total, Nullable<bool> estado)
        {
            var codigoClienteParameter = codigoCliente.HasValue ?
                new ObjectParameter("codigoCliente", codigoCliente) :
                new ObjectParameter("codigoCliente", typeof(int));
    
            var totalParameter = total.HasValue ?
                new ObjectParameter("total", total) :
                new ObjectParameter("total", typeof(decimal));
    
            var estadoParameter = estado.HasValue ?
                new ObjectParameter("estado", estado) :
                new ObjectParameter("estado", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_RegistrarPedido", codigoClienteParameter, totalParameter, estadoParameter);
        }
    
        public virtual int SP_RegistrarReclamo(string descripcion, Nullable<System.DateTime> fecha, Nullable<bool> estado, Nullable<int> codigoCliente)
        {
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("descripcion", descripcion) :
                new ObjectParameter("descripcion", typeof(string));
    
            var fechaParameter = fecha.HasValue ?
                new ObjectParameter("fecha", fecha) :
                new ObjectParameter("fecha", typeof(System.DateTime));
    
            var estadoParameter = estado.HasValue ?
                new ObjectParameter("estado", estado) :
                new ObjectParameter("estado", typeof(bool));
    
            var codigoClienteParameter = codigoCliente.HasValue ?
                new ObjectParameter("codigoCliente", codigoCliente) :
                new ObjectParameter("codigoCliente", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_RegistrarReclamo", descripcionParameter, fechaParameter, estadoParameter, codigoClienteParameter);
        }
    
        public virtual int SP_RegistrarSancion(Nullable<System.DateTime> fechaInicio, Nullable<System.DateTime> fechaFin, string motivo, Nullable<int> codigoCliente)
        {
            var fechaInicioParameter = fechaInicio.HasValue ?
                new ObjectParameter("fechaInicio", fechaInicio) :
                new ObjectParameter("fechaInicio", typeof(System.DateTime));
    
            var fechaFinParameter = fechaFin.HasValue ?
                new ObjectParameter("fechaFin", fechaFin) :
                new ObjectParameter("fechaFin", typeof(System.DateTime));
    
            var motivoParameter = motivo != null ?
                new ObjectParameter("motivo", motivo) :
                new ObjectParameter("motivo", typeof(string));
    
            var codigoClienteParameter = codigoCliente.HasValue ?
                new ObjectParameter("codigoCliente", codigoCliente) :
                new ObjectParameter("codigoCliente", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_RegistrarSancion", fechaInicioParameter, fechaFinParameter, motivoParameter, codigoClienteParameter);
        }
    
        public virtual int SP_RegistrarTrainer(string nombre, string apellido, string especialidad, Nullable<bool> disponibilidad)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            var apellidoParameter = apellido != null ?
                new ObjectParameter("apellido", apellido) :
                new ObjectParameter("apellido", typeof(string));
    
            var especialidadParameter = especialidad != null ?
                new ObjectParameter("especialidad", especialidad) :
                new ObjectParameter("especialidad", typeof(string));
    
            var disponibilidadParameter = disponibilidad.HasValue ?
                new ObjectParameter("disponibilidad", disponibilidad) :
                new ObjectParameter("disponibilidad", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_RegistrarTrainer", nombreParameter, apellidoParameter, especialidadParameter, disponibilidadParameter);
        }
    }
}
