//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvc_application
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class SmarfitEntities : DbContext
    {
        public SmarfitEntities()
            : base("name=SmarfitEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cliente> Cliente { get; set; }
        public virtual DbSet<DetallePedido> DetallePedido { get; set; }
        public virtual DbSet<Entrenamiento> Entrenamiento { get; set; }
        public virtual DbSet<Inscripciones> Inscripciones { get; set; }
        public virtual DbSet<Locales> Locales { get; set; }
        public virtual DbSet<Pedido> Pedido { get; set; }
        public virtual DbSet<Reclamo> Reclamo { get; set; }
        public virtual DbSet<Sancion> Sancion { get; set; }
        public virtual DbSet<Trainer> Trainer { get; set; }
    
        public virtual int SP_ActualizarPedido(Nullable<int> codigoPedido, Nullable<int> codigoCliente, Nullable<decimal> total, Nullable<bool> estado)
        {
            var codigoPedidoParameter = codigoPedido.HasValue ?
                new ObjectParameter("codigoPedido", codigoPedido) :
                new ObjectParameter("codigoPedido", typeof(int));
    
            var codigoClienteParameter = codigoCliente.HasValue ?
                new ObjectParameter("codigoCliente", codigoCliente) :
                new ObjectParameter("codigoCliente", typeof(int));
    
            var totalParameter = total.HasValue ?
                new ObjectParameter("total", total) :
                new ObjectParameter("total", typeof(decimal));
    
            var estadoParameter = estado.HasValue ?
                new ObjectParameter("estado", estado) :
                new ObjectParameter("estado", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_ActualizarPedido", codigoPedidoParameter, codigoClienteParameter, totalParameter, estadoParameter);
        }
    
        public virtual int SP_ActualizarSancion(Nullable<int> codigo, Nullable<System.DateTime> fechaInicio, Nullable<System.DateTime> fechaFin, string motivo, Nullable<int> codigoCliente, Nullable<bool> estado)
        {
            var codigoParameter = codigo.HasValue ?
                new ObjectParameter("codigo", codigo) :
                new ObjectParameter("codigo", typeof(int));
    
            var fechaInicioParameter = fechaInicio.HasValue ?
                new ObjectParameter("fechaInicio", fechaInicio) :
                new ObjectParameter("fechaInicio", typeof(System.DateTime));
    
            var fechaFinParameter = fechaFin.HasValue ?
                new ObjectParameter("fechaFin", fechaFin) :
                new ObjectParameter("fechaFin", typeof(System.DateTime));
    
            var motivoParameter = motivo != null ?
                new ObjectParameter("motivo", motivo) :
                new ObjectParameter("motivo", typeof(string));
    
            var codigoClienteParameter = codigoCliente.HasValue ?
                new ObjectParameter("codigoCliente", codigoCliente) :
                new ObjectParameter("codigoCliente", typeof(int));
    
            var estadoParameter = estado.HasValue ?
                new ObjectParameter("estado", estado) :
                new ObjectParameter("estado", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_ActualizarSancion", codigoParameter, fechaInicioParameter, fechaFinParameter, motivoParameter, codigoClienteParameter, estadoParameter);
        }
    
        public virtual ObjectResult<SP_BuscarPedidoXCodigo_Result> SP_BuscarPedidoXCodigo(Nullable<int> codigoPedido)
        {
            var codigoPedidoParameter = codigoPedido.HasValue ?
                new ObjectParameter("codigoPedido", codigoPedido) :
                new ObjectParameter("codigoPedido", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_BuscarPedidoXCodigo_Result>("SP_BuscarPedidoXCodigo", codigoPedidoParameter);
        }
    
        public virtual ObjectResult<SP_BuscarSancionXCodigo_Result> SP_BuscarSancionXCodigo(Nullable<int> codigo)
        {
            var codigoParameter = codigo.HasValue ?
                new ObjectParameter("codigo", codigo) :
                new ObjectParameter("codigo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_BuscarSancionXCodigo_Result>("SP_BuscarSancionXCodigo", codigoParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> SP_CodigoPedido()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("SP_CodigoPedido");
        }
    
        public virtual ObjectResult<Nullable<int>> SP_CodigoSancion()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("SP_CodigoSancion");
        }
    
        public virtual int SP_EliminarPedido(Nullable<int> codigoPedido)
        {
            var codigoPedidoParameter = codigoPedido.HasValue ?
                new ObjectParameter("codigoPedido", codigoPedido) :
                new ObjectParameter("codigoPedido", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_EliminarPedido", codigoPedidoParameter);
        }
    
        public virtual int SP_EliminarSancion(Nullable<int> codigo)
        {
            var codigoParameter = codigo.HasValue ?
                new ObjectParameter("codigo", codigo) :
                new ObjectParameter("codigo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_EliminarSancion", codigoParameter);
        }
    
        public virtual int SP_HabilitarPedido(Nullable<int> codigoPedido)
        {
            var codigoPedidoParameter = codigoPedido.HasValue ?
                new ObjectParameter("codigoPedido", codigoPedido) :
                new ObjectParameter("codigoPedido", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_HabilitarPedido", codigoPedidoParameter);
        }
    
        public virtual int SP_HabilitarSancion(Nullable<int> codigo)
        {
            var codigoParameter = codigo.HasValue ?
                new ObjectParameter("codigo", codigo) :
                new ObjectParameter("codigo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_HabilitarSancion", codigoParameter);
        }
    
        public virtual ObjectResult<SP_MostrarPedido_Result> SP_MostrarPedido()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_MostrarPedido_Result>("SP_MostrarPedido");
        }
    
        public virtual ObjectResult<SP_MostrarPedidoTodo_Result> SP_MostrarPedidoTodo()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_MostrarPedidoTodo_Result>("SP_MostrarPedidoTodo");
        }
    
        public virtual ObjectResult<SP_MostrarSancion_Result> SP_MostrarSancion()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_MostrarSancion_Result>("SP_MostrarSancion");
        }
    
        public virtual ObjectResult<SP_MostrarSancionTodo_Result> SP_MostrarSancionTodo()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_MostrarSancionTodo_Result>("SP_MostrarSancionTodo");
        }
    
        public virtual int SP_RegistrarPedido(Nullable<int> codigoCliente, Nullable<decimal> total, Nullable<bool> estado)
        {
            var codigoClienteParameter = codigoCliente.HasValue ?
                new ObjectParameter("codigoCliente", codigoCliente) :
                new ObjectParameter("codigoCliente", typeof(int));
    
            var totalParameter = total.HasValue ?
                new ObjectParameter("total", total) :
                new ObjectParameter("total", typeof(decimal));
    
            var estadoParameter = estado.HasValue ?
                new ObjectParameter("estado", estado) :
                new ObjectParameter("estado", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_RegistrarPedido", codigoClienteParameter, totalParameter, estadoParameter);
        }
    
        public virtual int SP_RegistrarReclamo(string descripcion, Nullable<System.DateTime> fecha, Nullable<bool> estado, Nullable<int> codigoCliente)
        {
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("descripcion", descripcion) :
                new ObjectParameter("descripcion", typeof(string));
    
            var fechaParameter = fecha.HasValue ?
                new ObjectParameter("fecha", fecha) :
                new ObjectParameter("fecha", typeof(System.DateTime));
    
            var estadoParameter = estado.HasValue ?
                new ObjectParameter("estado", estado) :
                new ObjectParameter("estado", typeof(bool));
    
            var codigoClienteParameter = codigoCliente.HasValue ?
                new ObjectParameter("codigoCliente", codigoCliente) :
                new ObjectParameter("codigoCliente", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_RegistrarReclamo", descripcionParameter, fechaParameter, estadoParameter, codigoClienteParameter);
        }
    }
}
